### ISSUE TITLE
UIAlertView is deprecated

### ISSUE THREAD

**Issue by pierrot10** [apache/cordova-plugin-dialogs#151] opened 2021-03-13 11:12 UTC
# UIAlertView' is deprecated

## Problem
UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead

### What does actually happen?
I recently installed Cordova 10
I am building a Android and IOS App with Cordova. From Xcode, when I run my App I have several warning
`UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead`

As I am novice, it's a bit hrad for me to adapt the plugin. There is a updated version or someone could help me solve it?
I am only using the plugin for the bip method. May be there is another way to bip the smartphone?

Thank for the support

### Environment, Platform, Device
jQuery, Cordova 10, Xcode 12, OSX10.15

**Comment by timbru31** [comment] 2021-03-13 13:36
Duplicate of #119  - the master is already updated but a release is pending. No ETA though when we make one.

**Closed by timbru31** 2021-03-13 13:36 UTC

**Comment by mathiasselleslach** [comment] 2021-05-01 09:20
@timbru31 , as #119 is already 3 years old by now, is there any reason there is no release yet?
Could you provide some details on how to move forward until then?
