### ISSUE TITLE
Alert notification does not working

### ISSUE THREAD

**Issue by jpfarberRTN** [apache/cordova-plugin-dialogs#118] opened 2018-12-07 17:00 UTC
I installed via: (Windows 10)
cordova plugin add cordova-plugin-dialogs

And when I use navigator.notification.alert() function, my code does not work, if I use only alert() (without navigator.notification) shows the classic alert but it works properly

Can You help me?
Thanks.

And I have this code:

// Javascript
function onDeviceReady() {
	navigator.notification.alert("Message", null, "Title", 'Ok');
	btnAppRegister = document.getElementById("btnAppRegister");
	btnAppRegister.addEventListener("click", function() {
		accessWebService();
	});
}

<div data-role="page" data-theme="a" id="pagConfigAppAccess">
	<div id="configContent" data-role="content" style="text-align: center;">
		<h3>Configure access</h3>
		<br />
		
		<div class="ui-field-contain">
			<label for="txtAppUser">User:</label>
			<input type="text" name="txtAppUser" id="txtAppUser" />
		</div>
		
		<div class="ui-field-contain">
			<label for="txtAppPass">Password:</label>
			<input type="password" name="txtAppPass" id="txtAppPass" />
		</div>
		
		<input type="button" id="btnAppRegister" value="Registrar" />
		
	</div>
</div>

**Comment by jpfarberRTN** [comment] 2018-12-07 17:23
Maybe this can help:
when I use cordova run android it shows this:

:app:compileDebugJavaWithJavacNote: C:\wamp\www\rtnsupport\platforms\android\app\src\main\java\org\apache\cordova\dialogs\Notification.java uses or overrides a deprecated API.

How can I fix this?

**Comment by jcesarmobile** [comment] 2022-09-06 22:14
Can you provide a sample app? I can't reproduce

**Comment by jcesarmobile** [comment] 2023-04-24 23:36
closing as no sample app was provided and I can't reproduce

**Closed by jcesarmobile** 2023-04-24 23:36 UTC
Labels: info-needed
